# Generated by Django 3.2.9 on 2021-11-22 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_toy'),
    ]

    operations = [
        migrations.AddField(
            model_name='pokemon',
            name='toys',
            field=models.ManyToManyField(to='main_app.Toy'),
        ),
    ]
